# Generated by Django 5.2.3 on 2026-02-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='condition',
            field=models.CharField(blank=True, choices=[('', 'Не обрано'), ('new', 'Новий'), ('used', 'Б/В')], max_length=10, null=True, verbose_name='Стан'),
        ),
    ]
