# Generated by Django 5.2.3 on 2026-01-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcement_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Переглядів'),
        ),
    ]
