# Generated by Django 5.2.3 on 2026-01-12 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_announcement_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('requires_condition', models.BooleanField(default=True, verbose_name='Потребує вказання стану')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'Новий'), ('used', 'Б/В')], max_length=10, null=True, verbose_name='Стан'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='announcement.category', verbose_name='Категорія'),
        ),
    ]
