# Generated by Django 5.2.3 on 2026-01-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_category_announcement_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Довгота'),
        ),
    ]
