# Generated by Django 5.2.3 on 2026-01-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Введіть номер телефону', max_length=20, null=True, unique=True, verbose_name='Номер телефону'),
        ),
    ]
